---
- name: install php
  apt:
    name: "{{ php_packages | list }}"
    update_cache: yes

- name: install composer
  apt:
    name: composer
    update_cache: yes

- name: install nginx
  apt:
    name: nginx
    update_cache: yes

- name: install posgresql
  apt:
    name: ['postgresql', 'postgresql-contrib']
    update_cache: yes
